### ISSUE TITLE
missing toml module

### ISSUE THREAD

**Issue by cheburakshu** [saltstack/heist#51]
Installed heist locally with 
`python3 setup.py install` and `pip3 install -r requirements.txt`

Got this traceback when I ran `heist`. Default `roster.cfg` was placed in `/etc/heist/rosters`.

The error went away when `toml` was manually installed.

```
raas@raas:/etc/heist/rosters$ heist
Traceback (most recent call last):
  File "/usr/local/bin/heist", line 11, in <module>
    load_entry_point('heist==2.2.0', 'console_scripts', 'heist')()
  File "/usr/local/lib/python3.6/dist-packages/heist/scripts.py", line 5, in start
    hub.pop.sub.add(dyne_name='heist')
  File "/usr/local/lib/python3.6/dist-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pop/mods/pop/sub.py", line 61, in add
    root._subs[subname]._sub_init(init)
  File "/usr/local/lib/python3.6/dist-packages/pop/hub.py", line 300, in _sub_init
    self._find_mod('init', match_only=True)
  File "/usr/local/lib/python3.6/dist-packages/pop/hub.py", line 331, in _find_mod
    self._load_item(iface, bname)
  File "/usr/local/lib/python3.6/dist-packages/pop/hub.py", line 365, in _load_item
    self._prep_mod(mod, iface, bname)
  File "/usr/local/lib/python3.6/dist-packages/pop/hub.py", line 406, in _prep_mod
    pop.loader.mod_init(self._hub, mod)
  File "/usr/local/lib/python3.6/dist-packages/pop/loader.py", line 206, in mod_init
    mod.__init__(hub)
  File "/usr/local/lib/python3.6/dist-packages/heist/heist/init.py", line 17, in __init__
    hub.pop.conf.integrate('heist', cli='heist', roots=True)
  File "/usr/local/lib/python3.6/dist-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pop/mods/pop/conf.py", line 26, in integrate
    logs=logs)
  File "/usr/local/lib/python3.6/dist-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pop/mods/conf/integrate.py", line 130, in load
    getattr(hub, f'conf.log.{log_plugin}.setup')(hub.OPT[primary])
  File "/usr/local/lib/python3.6/dist-packages/pop/contract.py", line 131, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pop/mods/conf/log/basic.py", line 18, in setup
    fh = logging.FileHandler(conf['log_file'])
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/etc/heist/rosters/heist.log'
raas@raas:/etc/heist/rosters$ sudo heist
[WARNING ] Failed to load python module 26d27c349f9c3077bb6df230016ebd30a123726612968818beb0042d72016a01.toml_file at path /usr/local/lib/python3.6/dist-packages/rend/rend/toml_file.py: ModuleNotFoundError("No module named 'toml'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pop/loader.py", line 126, in python
    return sfl.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/rend/rend/toml_file.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

[CRITICAL] Could not render the flat roster, error: Yaml render error: expected <block end>, but found '<scalar>'
raas@raas:/etc/heist/rosters$ pip3 insall toml
ERROR: unknown command "insall" - maybe you meant "install"
raas@raas:/etc/heist/rosters$ ^C
raas@raas:/etc/heist/rosters$ sudo pip3 install toml
WARNING: The directory '/home/raas/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/raas/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting toml
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Installing collected packages: toml
Successfully installed toml-0.10.0
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
raas@raas:/etc/heist/rosters$ sudo heist
[CRITICAL] Could not render the flat roster, error: Yaml render error: expected <block end>, but found '<scalar>'
raas@raas:/etc/heist/rosters$

```

**Comment by thatch45** [comment]
Thanks, this is an issue with the setup.py in rend that I need to fix as well as the fix in #58
